kind: Template
apiVersion: v1
metadata:
  labels:
    app: kubernetes-image-puller
  name: kubernetes-image-puller
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: create-daemonset
  rules:
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - create
    - delete
    - watch
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: 2019-04-04T23:20:55Z
    name: create-daemonset
    namespace: daemonset-test
    resourceVersion: "1516348"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/daemonset-test/rolebindings/daemonset-binding
    uid: 4c14fe24-5730-11e9-8bed-5254005a8b42
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: create-daemonset
  subjects:
  - kind: ServiceAccount
    name: che
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: che
